apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dagster-postgres-secret
  namespace: dagster
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: dagster-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: postgresql-password
      remoteRef: { key: dagster-dagster-postgres-secret, property: postgresql-password }

