apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-token
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: forgejo-runner-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef: { key: forgejo-forgejo-runner-token, property: token }

