apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-secrets
  namespace: gatus
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: gatus-secrets
    creationPolicy: Owner
  data:
    - secretKey: GATUS_TELEGRAM_CHAT_ID
      remoteRef: { key: gatus-gatus-secrets, property: GATUS_TELEGRAM_CHAT_ID }
    - secretKey: GATUS_TELEGRAM_TOKEN
      remoteRef: { key: gatus-gatus-secrets, property: GATUS_TELEGRAM_TOKEN }

