apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-tailnet
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: homepage-tailnet
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_ALLOWED_HOSTS
      remoteRef: { key: homepage-homepage-tailnet, property: HOMEPAGE_ALLOWED_HOSTS }
    - secretKey: HOMEPAGE_VAR_TAILNET
      remoteRef: { key: homepage-homepage-tailnet, property: HOMEPAGE_VAR_TAILNET }

