apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-api
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: immich-api
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef: { key: immich-immich-api, property: api-key }

