apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-generations
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: minio-generations
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef: { key: immich-minio-generations, property: access-key }
    - secretKey: secret-key
      remoteRef: { key: immich-minio-generations, property: secret-key }

