apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: immich-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef: { key: immich-immich-secret, property: DB_PASSWORD }

