apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inference-club-secrets
  namespace: inference-club-web
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: inference-club-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef: { key: inference-club-web-inference-club-secrets, property: DATABASE_URL }
    - secretKey: DJANGO_SECRET_KEY
      remoteRef: { key: inference-club-web-inference-club-secrets, property: DJANGO_SECRET_KEY }
    - secretKey: OBJECT_STORAGE_ACCESS_KEY
      remoteRef: { key: inference-club-web-inference-club-secrets, property: OBJECT_STORAGE_ACCESS_KEY }
    - secretKey: OBJECT_STORAGE_SECRET_KEY
      remoteRef: { key: inference-club-web-inference-club-secrets, property: OBJECT_STORAGE_SECRET_KEY }

