apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyter-auth
  namespace: jupyter
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: jupyter-auth
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef: { key: jupyter-jupyter-auth, property: token }

