apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manyfold-secret
  namespace: manyfold
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: manyfold-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef: { key: manyfold-manyfold-secret, property: SECRET_KEY_BASE }

