apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: milvus-minio
  namespace: milvus
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: milvus-minio
    creationPolicy: Owner
  data:
    - secretKey: accesskey
      remoteRef: { key: milvus-milvus-minio, property: accesskey }
    - secretKey: secretkey
      remoteRef: { key: milvus-milvus-minio, property: secretkey }

