apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-backups-secrets
  namespace: minio-backups
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: minio-backups-secrets
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef: { key: minio-backups-minio-backups-secrets, property: root-password }
    - secretKey: root-user
      remoteRef: { key: minio-backups-minio-backups-secrets, property: root-user }

