apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: n8n-encryption-key
    creationPolicy: Owner
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef: { key: n8n-n8n-encryption-key, property: N8N_ENCRYPTION_KEY }

