apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phoenix-postgresql
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: phoenix-postgresql
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef: { key: observability-phoenix-postgresql, property: POSTGRES_DB }
    - secretKey: POSTGRES_PASSWORD
      remoteRef: { key: observability-phoenix-postgresql, property: POSTGRES_PASSWORD }
    - secretKey: USERDB_PASSWORD
      remoteRef: { key: observability-phoenix-postgresql, property: USERDB_PASSWORD }
    - secretKey: USERDB_USER
      remoteRef: { key: observability-phoenix-postgresql, property: USERDB_USER }

