apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: parseable-env-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: parseable-env-secret
    creationPolicy: Owner
  data:
    - secretKey: addr
      remoteRef: { key: observability-parseable-env-secret, property: addr }
    - secretKey: username
      remoteRef: { key: observability-parseable-env-secret, property: username }
    - secretKey: password
      remoteRef: { key: observability-parseable-env-secret, property: password }
