apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openobserve-root
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: openobserve-root
    creationPolicy: Owner
  data:
    - secretKey: ZO_ROOT_USER_EMAIL
      remoteRef: { key: observability-openobserve-root, property: ZO_ROOT_USER_EMAIL }
    - secretKey: ZO_ROOT_USER_PASSWORD
      remoteRef: { key: observability-openobserve-root, property: ZO_ROOT_USER_PASSWORD }
