apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phoenix-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: phoenix-secret
    creationPolicy: Owner
  data:
    - secretKey: PHOENIX_ADMIN_SECRET
      remoteRef: { key: observability-phoenix-secret, property: PHOENIX_ADMIN_SECRET }
    - secretKey: PHOENIX_DEFAULT_ADMIN_INITIAL_PASSWORD
      remoteRef: { key: observability-phoenix-secret, property: PHOENIX_DEFAULT_ADMIN_INITIAL_PASSWORD }
    - secretKey: PHOENIX_POSTGRES_PASSWORD
      remoteRef: { key: observability-phoenix-secret, property: PHOENIX_POSTGRES_PASSWORD }
    - secretKey: PHOENIX_SECRET
      remoteRef: { key: observability-phoenix-secret, property: PHOENIX_SECRET }
    - secretKey: PHOENIX_SMTP_PASSWORD
      remoteRef: { key: observability-phoenix-secret, property: PHOENIX_SMTP_PASSWORD }

