apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-litellm
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: openwebui-litellm
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef: { key: open-webui-openwebui-litellm, property: api-key }

