apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-secrets
  namespace: paperless
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: backup-secrets
    creationPolicy: Owner
  data:
    - secretKey: restic-password
      remoteRef: { key: paperless-backup-secrets, property: restic-password }
    - secretKey: s3-access-key
      remoteRef: { key: paperless-backup-secrets, property: s3-access-key }
    - secretKey: s3-secret-key
      remoteRef: { key: paperless-backup-secrets, property: s3-secret-key }

