apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: paperless
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: paperless-secret
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef: { key: paperless-paperless-secret, property: ADMIN_PASSWORD }
    - secretKey: DBPASS
      remoteRef: { key: paperless-paperless-secret, property: DBPASS }
    - secretKey: SECRET_KEY
      remoteRef: { key: paperless-paperless-secret, property: SECRET_KEY }

