apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-secrets
  namespace: pihole
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: pihole-secrets
    creationPolicy: Owner
  data:
    - secretKey: WEBPASSWORD
      remoteRef: { key: pihole-pihole-secrets, property: WEBPASSWORD }

