apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-minio
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: platform-minio
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef: { key: platform-platform-minio, property: root-password }
    - secretKey: root-user
      remoteRef: { key: platform-platform-minio, property: root-user }

