apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: github-token
      remoteRef: { key: renovate-renovate-secrets, property: github-token }
    - secretKey: token
      remoteRef: { key: renovate-renovate-secrets, property: token }

