apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scrutiny-secrets
  namespace: scrutiny
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: scrutiny-secrets
    creationPolicy: Owner
  data:
    - secretKey: influx-password
      remoteRef: { key: scrutiny-scrutiny-secrets, property: influx-password }
    - secretKey: influx-token
      remoteRef: { key: scrutiny-scrutiny-secrets, property: influx-token }
    - secretKey: notify-urls
      remoteRef: { key: scrutiny-scrutiny-secrets, property: notify-urls }

