apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-secrets
  namespace: speedtest
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vaultwarden, kind: ClusterSecretStore }
  target:
    name: speedtest-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef: { key: speedtest-speedtest-secrets, property: APP_KEY }

